on:
    push:
        branches: [master]

jobs:
  release_notifier_job:
    runs-on: ubuntu-latest
    name: Release Notifier
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v1
      - name: Fetch releases
        uses: ./ # Uses an action in the root directory
        id: notify
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-message: '{"channel":"C1234567890","text":"Hello world"}'
      # # Use the output from the `notify` step
      - name: Response from slack post message
        run: echo "The response was ${{ steps.notify.outputs.slack-reponse }}"